feat: add getPreviousMessagesV2 and getRecentMessagesV2
evex-dev/linejs pull request #25
Opened 2024-09-09 15:18 UTC by MocA-Love

love

2024-09-09 23:15 UTC, EdamAme-x requested changes

2024-09-09 23:15 UTC, EdamAme-x commented on packages/client/clients/internal/talk-client.ts
> +		time
```suggestion

```
Don't need this line

2024-09-09 23:59 UTC, MocA-Love commented
gogo

2024-09-10 00:16 UTC, MocA-Love commented
add getRecentMessagesV2

2024-09-10 00:25 UTC, EdamAme-x approved these changes

2024-09-10 00:25 UTC, EdamAme-x commented
LGTM!

2024-09-10 00:25 UTC, merged